### ISSUE TITLE
show full file path

### ISSUE THREAD

**Issue by yomed** [lesshint/reporter-stylish#1]
Hi, would you consider updating this reporter to use `result.fullPath` instead of `result.file`? I have a modularized project where each component has a `style.less` file, so the lesshint output looks like:

```
Warning: style.less: line 43, col 9, propertyOrdering: Property ordering is not alphabetized
Warning: style.less: line 46, col 19, spaceAfterPropertyColon: Colon after property name should be followed by one space.
Warning: style.less: line 9, col 5, propertyOrdering: Property ordering is not alphabetized
Warning: style.less: line 18, col 17, spaceAfterPropertyColon: Colon after property name should be followed by one space.
Warning: style.less: line 20, col 9, propertyOrdering: Property ordering is not alphabetized
```

**Comment by jwilsson** [comment]
Hi!
It's tricky, since changing that could be considered a breaking change and pretty noisy. A middle-way (which would still be somewhat breaking) is to print the relative path. 

But it's of course always possible for you to fork this repo and use that instead, we're not going to make any other bigger changes here anyway so it's going to be stable for you.

**Comment by yomed** [comment]
Hey @jwilsson, thanks for getting back to me. I didn't think this would be a controversial change since all the other linters seem to print the full path (eslint, jshint, jscs, etc). It's a common situation in node where you have lots of files named `index.js`.

My eslint output looks like:
```
/Users/user-name/path/project/src/index.js
  12:25  error    Missing semicolon                           semi
  89:31  warning  'a' is already declared in the upper scope  no-shadow
  89:34  warning  'b' is already declared in the upper scope  no-shadow
```

I could fork it and use that, but I was hoping to pull this into a larger repo that shouldn't rely on a one-off fix fork like that. Alternatively, I could publish a different reporter, but was hoping I wouldn't need to. Let me know what you think!

**Comment by jwilsson** [comment]
@yomed Sorry if it came off as controversial. Forgot about how we handled things in the main `lesshint` project (Monday morning 😄 ). That's why I didn't wanted to bump the major version, but since there's no connection there it's fine.

Anyway, after thinking about it a bit more I wanted to check with you if showing the file path relative to `process.cwd()`, i.e. `src/css/module/style.css` would be enough? If so, I'd be happy to review a PR for it and then we simply bump the major version.

**Comment by yomed** [comment]
@jwilsson That sounds good. It looks like `result.fullPath` is actually relative paths at the moment (does not include `/Users/...`), but you'd have more context on that than I would:
https://github.com/lesshint/lesshint/blob/18944083bbd69dc0f3d607f24617732a15093e2e/lib/lesshint.js#L18

In that case we can just use `result.fullPath`. I think to reduce noise we could avoid repeating the filename for every error like above, but I guess that's slightly more involved.

**Comment by jwilsson** [comment]
`result.fullPath` contains whatever that's passed to it, if you're running from Gulp for example it'll be a full path but when passed a relative path from the CLI it'll be relative.

Guess we should correct that in `lesshint` in the future.

**Comment by jwilsson** [comment]
Hi again!
I don't know if you're even interested in this anymore. I had forgot about it but saw in when doing some cleaning here. 

But in case you or someone else stumbles upon this in the future, there's a [reporter-stylisher](https://www.npmjs.com/package/lesshint-reporter-stylisher) which shows the full path to the offending files.

Cheers!
